// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHU709lniILK0vBV7PM5RV4FM2mwK7mr4',
    appId: '1:106355117037:web:57fc886857ff772154f5e4',
    messagingSenderId: '106355117037',
    projectId: 'tfgdam-e651f',
    authDomain: 'tfgdam-e651f.firebaseapp.com',
    storageBucket: 'tfgdam-e651f.appspot.com',
    measurementId: 'G-9CCHNQLXTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByu23v-F9d_JDUpQcZhNqa-kRvkmw5sHQ',
    appId: '1:106355117037:android:4b4dae2a221fd7f354f5e4',
    messagingSenderId: '106355117037',
    projectId: 'tfgdam-e651f',
    storageBucket: 'tfgdam-e651f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEf0c0EYi4-XkFjXhfNSsyOFl_xPg8_vE',
    appId: '1:106355117037:ios:d9a2911e2cfa878254f5e4',
    messagingSenderId: '106355117037',
    projectId: 'tfgdam-e651f',
    storageBucket: 'tfgdam-e651f.appspot.com',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEf0c0EYi4-XkFjXhfNSsyOFl_xPg8_vE',
    appId: '1:106355117037:ios:d9a2911e2cfa878254f5e4',
    messagingSenderId: '106355117037',
    projectId: 'tfgdam-e651f',
    storageBucket: 'tfgdam-e651f.appspot.com',
    iosBundleId: 'com.example.tfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHU709lniILK0vBV7PM5RV4FM2mwK7mr4',
    appId: '1:106355117037:web:2af56e2310fa14aa54f5e4',
    messagingSenderId: '106355117037',
    projectId: 'tfgdam-e651f',
    authDomain: 'tfgdam-e651f.firebaseapp.com',
    storageBucket: 'tfgdam-e651f.appspot.com',
    measurementId: 'G-RSWQEEGXVL',
  );

}